import pygame
import sys
import os # For os.path.join if used for SPELLS_FILE path construction

# Import from our new utility/config files first
from game_config import * # TILE_SIZE, screen dimensions, FPS, colors etc.
from game_utils import roll_dice_expression # load_json, load_sprite are not directly used in game_loop.py but by its imports
from game_effects import spell_sound, melee_sound, arrow_sound, levelup_sound, frost_sound # Sounds
# Visual effects are called by spell_system or common_b_s legacy spells, not directly here.

# Import core game modules
import common_b_s # For assets_data, and items_list for now
from common_b_s import (
    add_message, update_message_queue, MessageCategory,
    draw_bordered_text, draw_attack_prompt, draw_right_panel, draw_bottom_panel,
    handle_scroll_events, get_memory_usage, loot_drop_sprite,
    cast_spell, # This is the legacy common_b_s.cast_spell
    spells_dialogue, # This is the legacy common_b_s.spells_dialogue
    save_game, load_game, # These are from common_b_s, originally from game_state_manager
    handle_monster_turn, # Legacy monster turn from common_b_s
    Dungeon, items_list # Dungeon class, items_list for loot
)

import debug_system # For debug_system.key_state, etc.
from debug_system import debug_console

from game_state_manager import GameState, game_state_manager, \
                               transition_from_hub_to_dungeon, \
                               handle_dungeon_level_transition, \
                               handle_dungeon_map_transition
                               # handle_test_arena_teleport (Commented out as test arena features are commented out in loop)

from player import Player
from novamagus_hub import nova_magus_hub # For run_hub, transition_to_dungeon flag

from Data.condition_system import condition_manager
from Data.spell_bridge import update_spells_dialogue # New spell dialogue UI

# Import the refactored process_monster_death
from game_logic_utils import process_monster_death as util_process_monster_death


def process_game_turn(player, dungeon):
    debug_console.add_message(f"game_loop.process_game_turn: Using condition_manager with current_turn: {condition_manager.current_turn}", "DEBUG")
    condition_messages = condition_manager.process_turn([player] + dungeon.monsters)
    for msg in condition_messages:
        add_message(msg)


def combat(player_char, monster_char, dungeon_instance_ref): # Renamed params for clarity
    combat_messages = []

    # Access common_b_s attributes through the imported module common_b_s
    player_str_mod = player_char.calculate_modifier(player_char.get_effective_ability("strength"))
    monster_str_mod = monster_char.to_hit

    # roll_dice_expression is imported directly from game_utils
    player_initiative = roll_dice_expression("1d10") + player_char.calculate_modifier(player_char.get_effective_ability("dexterity"))
    monster_initiative = roll_dice_expression("1d10") + monster_char.to_hit

    if player_initiative > monster_initiative:
        attacker, defender = player_char, monster_char
        combat_messages.append(f"{player_char.name} goes first!")
    else:
        attacker, defender = monster_char, player_char
        combat_messages.append(f"{monster_char.name} goes first!")

    while attacker.hit_points > 0 and defender.hit_points > 0: # Check attacker's HP as well
        if attacker == player_char:
            attack_roll = roll_dice_expression("1d20") + player_char.calculate_modifier(player_char.get_effective_ability("strength"))
        else: # Monster is attacker
            attack_roll = roll_dice_expression("1d20") + monster_char.to_hit

        if attack_roll >= defender.get_effective_ac():
            if attacker == player_char:
                damage = player_char.get_effective_damage()
            else: # Monster is attacker
                damage = monster_char.get_effective_damage()

            defender.hit_points -= damage
            combat_messages.append(f"{attacker.name} hits {defender.name} for {damage} damage!")
            melee_sound.play() # melee_sound from game_effects
        else:
            combat_messages.append(f"{attacker.name} misses {defender.name}!")

        # Swap attacker and defender
        attacker, defender = defender, attacker

    if player_char.hit_points <= 0:
        combat_messages.append("YOU have Died.")
        player_char.sprite = load_sprite(common_b_s.assets_data['sprites']['heroes']['warrior']['dead']) # load_sprite from game_utils
        player_char.is_dead = True # Explicitly mark player as dead
        game_state_manager.set_state(GameState.GAME_OVER)
    elif monster_char.hit_points <= 0:
        monster_char.is_dead = True # Mark monster as dead for main loop processing
        # Death messages like "Monster defeated" will be generated by util_process_monster_death
        # util_process_monster_death will be called in the main loop based on is_dead flag
        combat_messages.append(f"{monster_char.name} is defeated in direct combat!")


    return combat_messages

def run_game_loop(screen, clock, player, game_dungeon, initial_game_state_enum):
    running = True
    combat_occurred = False # General flag for whether combat happened in a turn cycle
    combat_occurred_prompt = False # Flag for Y/N combat prompt specifically
    last_debug_update = 0

    # Ensure game_state_manager is set with the initial state if this loop is the authority
    # game_state_manager.set_state(initial_game_state_enum) # Or assume it's set by caller

    current_event_for_activation = None # For test_arena (currently commented out)

    while running:
        _current_game_state_enum = game_state_manager.get_state()

        key_states = pygame.key.get_pressed()

        if hasattr(debug_system, 'key_state'):
            debug_system.key_state["F1"] = key_states[pygame.K_F1]
            debug_system.key_state["T"] = key_states[pygame.K_t] # Example, add others if needed

        if _current_game_state_enum == GameState.HUB:
            nova_magus_hub.run_hub(screen, clock, player)
            if nova_magus_hub.transition_to_dungeon:
                game_dungeon = transition_from_hub_to_dungeon(player, screen, clock)
                game_state_manager.set_state(GameState.PLAYING)

        update_message_queue()

        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False

            # Pass event to Nova Magus Hub if it has a handler (it doesn't in current structure)
            # if hasattr(nova_magus_hub, 'handle_event'):
            #    nova_magus_hub.handle_event(event)

            if event.type == pygame.USEREVENT + 1:
                levelup_sound.play() # from game_effects
                pygame.time.set_timer(pygame.USEREVENT + 1, 0)

            if event.type == pygame.KEYDOWN:
                key_name = pygame.key.name(event.key)
                if hasattr(debug_system, 'test_arena_logger') and hasattr(debug_system.test_arena_logger, 'debug'):
                    debug_system.test_arena_logger.debug(f"Key pressed: {key_name}")
                if hasattr(debug_system, 'keys_pressed'):
                    debug_system.keys_pressed.append(key_name)
                    if len(debug_system.keys_pressed) > 10: debug_system.keys_pressed.pop(0)

                if event.key == pygame.K_d:
                    debug_console.toggle()
                    add_message("Debug console toggled", WHITE, MessageCategory.DEBUG)

                if debug_console.visible and debug_console.handle_scroll(event): continue

                # Global scroll for message panel (if not handled by console)
                # handle_scroll_events is from common_b_s, check if it's needed if console handles scroll
                # For now, assume it might be for a different scrollable area or if console doesn't consume.
                handle_scroll_events(event)

                moved_this_turn = False

                current_loop_state_enum = game_state_manager.get_state()

                if current_loop_state_enum == GameState.PLAYING:
                    # Player movement and actions
                    action_taken_by_player = False
                    if event.key in [pygame.K_UP, pygame.K_DOWN, pygame.K_LEFT, pygame.K_RIGHT, pygame.K_w, pygame.K_s, pygame.K_a, pygame.K_d]:
                        dx, dy = 0,0
                        if event.key == pygame.K_UP or event.key == pygame.K_w: dy = -1
                        elif event.key == pygame.K_DOWN or event.key == pygame.K_s: dy = 1
                        elif event.key == pygame.K_LEFT or event.key == pygame.K_a: dx = -1
                        elif event.key == pygame.K_RIGHT or event.key == pygame.K_d: dx = 1

                        # Player.move takes grid dx, dy. Original blade_sigil used pixel TILE_SIZE.
                        # Assuming player.move handles grid-based movement now.
                        move_result = player.move(dx, dy, game_dungeon)

                        success, transition_type, message, destination_map = False, None, "", None
                        if len(move_result) == 4: success, transition_type, destination_map, message = move_result
                        elif len(move_result) == 3: success, transition_type, message = move_result

                        if success: action_taken_by_player = True
                        if message and message.strip(): add_message(message)

                        if success and transition_type == "map_transition" and destination_map is not None:
                            game_dungeon = handle_dungeon_map_transition(player, game_dungeon, destination_map)
                        elif success and transition_type == "level_transition":
                            game_dungeon = handle_dungeon_level_transition(player, game_dungeon)

                    elif event.key == pygame.K_SPACE: # Player waits
                        action_taken_by_player = True
                        add_message(f"{player.name} waits.", MessageCategory.INFO)

                    elif event.key == pygame.K_i:
                        game_state_manager.set_state(GameState.INVENTORY)
                        add_message("Inventory Opened.", MessageCategory.GAME_EVENT)
                    elif event.key == pygame.K_c: # Character Sheet
                        game_state_manager.set_state(GameState.CHARACTER_SHEET)
                        add_message("Character Sheet Opened.", MessageCategory.GAME_EVENT)
                    elif event.key == pygame.K_ESCAPE: # Pause Menu
                        game_state_manager.set_state(GameState.PAUSE_MENU)
                        add_message("Pause Menu Opened.", MessageCategory.GAME_EVENT)

                    elif event.key == pygame.K_y and combat_occurred_prompt:
                        # Find adjacent monster for combat
                        target_monster = None
                        player_tile_x = player.position[0] // TILE_SIZE
                        player_tile_y = player.position[1] // TILE_SIZE
                        for m in game_dungeon.monsters:
                            if m.is_alive:
                                monster_tile_x = m.position[0] // TILE_SIZE
                                monster_tile_y = m.position[1] // TILE_SIZE
                                if abs(player_tile_x - monster_tile_x) + abs(player_tile_y - monster_tile_y) == 1:
                                    target_monster = m; break
                        if target_monster:
                            combat_log = combat(player, target_monster, game_dungeon)
                            for log_msg in combat_log: add_message(log_msg, MessageCategory.COMBAT)
                            action_taken_by_player = True
                        combat_occurred_prompt = False # Consume the prompt

                    elif event.key == pygame.K_n and combat_occurred_prompt:
                        combat_occurred_prompt = False
                        add_message("You chose not to attack.", MessageCategory.GAME_EVENT)

                    elif event.key == pygame.K_x: # Cast spell
                        selected_spell = None
                        try: selected_spell = update_spells_dialogue(screen, player, clock)
                        except Exception as e: debug_console.add_message(f"Spell UI Error: {e}", "ERROR"); selected_spell = spells_dialogue(screen, player, clock) # Fallback

                        if selected_spell:
                            # Simplified targeting: first living monster if not self/friendly
                            target_for_spell = player # Default for self/friendly
                            if spell_helpers.get_spell_targets(selected_spell) not in ["self", "allies"]: # spell_helpers from Data
                                target_for_spell = next((m for m in game_dungeon.monsters if m.is_alive), None)
                                if not target_for_spell: add_message("No valid enemy targets for spell.", MessageCategory.INFO)

                            if target_for_spell:
                                # cast_spell is the legacy one from common_b_s, which internally calls spell_bridge
                                spell_cast_messages = cast_spell(player, target_for_spell, selected_spell["name"], game_dungeon)
                                for msg in spell_cast_messages: add_message(msg) # Messages from spell system
                                action_taken_by_player = True

                    # ... (Other key actions: K_o, K_p, K_u for doors/chests, K_h for help, F5/F9 for save/load) ...
                    # These would set action_taken_by_player = True

                    if action_taken_by_player:
                        process_game_turn(player, game_dungeon)
                        # Monster turns are part of process_game_turn or called after it
                        for monster_obj in game_dungeon.monsters:
                            if monster_obj.hit_points > 0 and not getattr(monster_obj, '_was_incapacitated_this_turn', False):
                                handle_monster_turn(monster_obj, player, game_dungeon) # Legacy from common_b_s

                        # After all actions (player + monsters), check for deaths from this turn's events
                        for m_obj in list(game_dungeon.monsters):
                            if m_obj.hit_points <= 0 and not getattr(m_obj, 'death_processed_this_turn_final', False):
                                death_messages_loop = util_process_monster_death(m_obj, player, game_dungeon, add_message, items_list)
                                for msg in death_messages_loop: add_message(msg)
                                m_obj.death_processed_this_turn_final = True # Ensure it's processed only once per turn cycle

                        if player.is_dead: # Check if player died during monster turns or DoTs
                             game_state_manager.set_state(GameState.GAME_OVER)
                             add_message("You have succumbed to your wounds!", MessageCategory.GAME_EVENT)

                        # Reset one-turn flags for all monsters
                        for m_obj in game_dungeon.monsters:
                            if hasattr(m_obj, 'death_processed_this_turn_final'):
                                delattr(m_obj, 'death_processed_this_turn_final')
                            if hasattr(m_obj, '_was_incapacitated_this_turn'): # Reset for next turn by condition_manager
                                m_obj._was_incapacitated_this_turn = False


                elif current_loop_state_enum == GameState.PAUSED:
                    if event.key == pygame.K_p: game_state_manager.set_state(GameState.PLAYING); debug_console.add_message("Game Resumed.", "GAME_EVENT")
                elif current_loop_state_enum == GameState.INVENTORY:
                    if event.key == pygame.K_i: game_state_manager.set_state(GameState.PLAYING); debug_console.add_message("Inventory Closed.", "GAME_EVENT")
                elif current_loop_state_enum == GameState.CHARACTER_SHEET:
                    if event.key == pygame.K_c: game_state_manager.set_state(GameState.PLAYING); debug_console.add_message("Character Sheet Closed.", "GAME_EVENT")
                elif current_loop_state_enum == GameState.PAUSE_MENU:
                    if event.key == pygame.K_ESCAPE: game_state_manager.set_state(GameState.PLAYING); debug_console.add_message("Pause Menu Closed.", "GAME_EVENT")
                elif current_loop_state_enum == GameState.GAME_OVER:
                    if event.type == pygame.KEYDOWN: running = False; debug_console.add_message("Exiting Game Over.", "GAME_EVENT")

        # --- Game State Updates (continuous) ---
        if _current_game_state_enum == GameState.PLAYING:
            player_tile_x = player.position[0] // TILE_SIZE
            player_tile_y = player.position[1] // TILE_SIZE
            for drop in game_dungeon.dropped_items[:]:
                if player_tile_x == (drop['position'][0] // TILE_SIZE) and player_tile_y == (drop['position'][1] // TILE_SIZE):
                    player.pickup_item(drop['item'])
                    game_dungeon.dropped_items.remove(drop)
                    # add_message already handled by pickup_item
            chest_coords = (player_tile_x, player_tile_y)
            if chest_coords in game_dungeon.chests:
                chest = game_dungeon.chests[chest_coords]
                if chest.open and (len(chest.contents) > 0 or chest.gold > 0):
                    if chest.gold > 0: player.gold += chest.gold; add_message(f"Found {chest.gold} gold!", MessageCategory.ITEM); chest.gold = 0
                    for item_in_chest in chest.contents[:]: player.pickup_item(item_in_chest) # pickup_item handles messages
                    chest.contents = []

        # --- Drawing Code ---
        screen.fill(BLACK)
        current_draw_state = game_state_manager.get_state()

        if current_draw_state == GameState.PLAYING:
            game_dungeon.draw(screen, player.position[0], player.position[1]) # Pass player's pixel coords
            player.draw(screen, game_dungeon.tile_size, getattr(game_dungeon, 'camera_offset_x',0), getattr(game_dungeon, 'camera_offset_y',0))
            for m_obj in game_dungeon.monsters:
                 if not m_obj.is_dead : # Only draw living monsters this way
                    m_obj.draw(screen, game_dungeon.tile_size, getattr(game_dungeon, 'camera_offset_x',0), getattr(game_dungeon, 'camera_offset_y',0))

            draw_right_panel(screen, player, DUNGEON_PLAYABLE_AREA_WIDTH, DUNGEON_PLAYABLE_AREA_HEIGHT, DUNGEON_RIGHT_PANEL_WIDTH)
            draw_bottom_panel(screen, DUNGEON_PLAYABLE_AREA_HEIGHT, DUNGEON_SCREEN_WIDTH, DUNGEON_BOTTOM_PANEL_HEIGHT)

            # Combat prompt logic (simplified from original blade_sigil)
            # Reset prompt flag each frame unless a monster is adjacent
            new_combat_prompt_needed = False
            player_tile_x = player.position[0] // TILE_SIZE
            player_tile_y = player.position[1] // TILE_SIZE
            for m_obj in game_dungeon.monsters:
                if m_obj.is_alive:
                    monster_tile_x = m_obj.position[0] // TILE_SIZE
                    monster_tile_y = m_obj.position[1] // TILE_SIZE
                    if abs(player_tile_x - monster_tile_x) + abs(player_tile_y - monster_tile_y) == 1:
                        if not combat_occurred_prompt : # Only draw if not already in Y/N decision
                             draw_attack_prompt(screen, m_obj.name)
                        new_combat_prompt_needed = True
                        break
            combat_occurred_prompt = new_combat_prompt_needed


        elif current_draw_state == GameState.PAUSED:
            game_dungeon.draw(screen, player.position[0], player.position[1])
            player.draw(screen, game_dungeon.tile_size, getattr(game_dungeon, 'camera_offset_x',0), getattr(game_dungeon, 'camera_offset_y',0))
            for m_obj in game_dungeon.monsters:
                if not m_obj.is_dead : m_obj.draw(screen, game_dungeon.tile_size, getattr(game_dungeon, 'camera_offset_x',0), getattr(game_dungeon, 'camera_offset_y',0))
            draw_bordered_text(screen, "PAUSED", DUNGEON_SCREEN_WIDTH // 2, DUNGEON_SCREEN_HEIGHT // 2, RED, font_size=48)

        elif current_draw_state == GameState.INVENTORY:
            # Inventory screen would typically be a full screen UI, or an overlay.
            # If it's a full screen UI, it handles its own drawing.
            # If it's an overlay, draw game then overlay.
            # common_b_s.manage_inventory is called from blade_sigil.py which has its own loop.
            # This state means game_loop might pause, or inventory is an overlay.
            # For now, assume it's an overlay state.
            game_dungeon.draw(screen, player.position[0], player.position[1])
            draw_bordered_text(screen, "INVENTORY (I to close)", DUNGEON_SCREEN_WIDTH // 2, DUNGEON_SCREEN_HEIGHT // 2, WHITE, font_size=30)

        elif current_draw_state == GameState.CHARACTER_SHEET:
            game_dungeon.draw(screen, player.position[0], player.position[1])
            draw_bordered_text(screen, "CHARACTER (C to close)", DUNGEON_SCREEN_WIDTH // 2, DUNGEON_SCREEN_HEIGHT // 2, WHITE, font_size=30)

        elif current_draw_state == GameState.PAUSE_MENU:
            game_dungeon.draw(screen, player.position[0], player.position[1])
            draw_bordered_text(screen, "PAUSE MENU (ESC to resume)", DUNGEON_SCREEN_WIDTH // 2, DUNGEON_SCREEN_HEIGHT // 2, YELLOW, font_size=30)

        elif current_draw_state == GameState.GAME_OVER:
            draw_bordered_text(screen, "GAME OVER", DUNGEON_SCREEN_WIDTH // 2, DUNGEON_SCREEN_HEIGHT // 2 - 50, RED, font_size=60)
            draw_bordered_text(screen, "Press any key to continue", DUNGEON_SCREEN_WIDTH // 2, DUNGEON_SCREEN_HEIGHT // 2 + 50, WHITE, font_size=30)

        current_time_ticks = pygame.time.get_ticks()
        if current_time_ticks - last_debug_update > 5000: # 5 seconds
            if debug_console.visible:
                fps_val = clock.get_fps()
                mem_info = get_memory_usage()
                add_message(f"FPS: {fps_val:.1f}, {mem_info}", (150,150,255), MessageCategory.DEBUG)
                if player:
                     add_message(f"Player: HP {player.hit_points}/{player.max_hit_points}, SP {player.spell_points}/{getattr(player, 'max_spell_points', 'N/A')}",
                                  (200,255,200), MessageCategory.DEBUG)
                if game_dungeon and (current_draw_state == GameState.PLAYING or current_draw_state == GameState.PAUSED) :
                    counts = (len(game_dungeon.monsters), len(game_dungeon.dropped_items), len(game_dungeon.chests))
                    add_message(f"Entities: {counts[0]} monsters, {counts[1]} items, {counts[2]} chests",
                              (200,200,255), MessageCategory.DEBUG)
            last_debug_update = current_time_ticks
        debug_console.draw(screen)

        pygame.display.flip()
        clock.tick(FPS)

    pygame.quit()
    sys.exit()
